/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iitd_socket_UdpSocketX */

#ifndef _Included_com_iitd_socket_UdpSocketX
#define _Included_com_iitd_socket_UdpSocketX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iitd_socket_UdpSocketX
 * Method:    sendUdpPacket
 * Signature: (Lcom/iitd/packetx/Ipv4Header;Lcom/iitd/packetx/UdpHeader;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iitd_socket_UdpSocketX_sendUdpPacket
  (JNIEnv *, jobject, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
